# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  BUILD_TYPE: Debug

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        
      - name: Install OpenGL lib
        run: sudo apt-get install -y libglew-dev mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglfw3-dev python3-pcl pcl-tools libpcl-dev
        
#       - name: Install OpenCV 4.2.0
#         uses: Dovyski/setup-opencv-action@v1
#         with: 
#           opencv-version: 4.2.0
#           WITH_V4L: ON
#           WITH_QT: ON
#           WITH_OPENGL: ON
        
      - name: Configure CMake
        env:
          CMAKE_PREFIX_PATH: ${{env.Qt5_Dir}}
        run: cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -B '${{github.workspace}}'/build
      - name: Build
        run: cmake --build '${{github.workspace}}'/build --target GreenHouseAR
        
        

